### ISSUE TITLE
InvalidConfigurationException after split brain recovery

### ISSUE THREAD

**Issue by fschuh** [hazelcast/hazelcast-aws#15]
After a split brain, in one of our server nodes Hazelcast started printing the following error to our logs:

```
com.hazelcast.config.InvalidConfigurationException: You should only define one of `<iam-role>` and `<access-key>`
        at com.hazelcast.aws.impl.DescribeInstances.checkKeysFromIamRoles(DescribeInstances.java:83) ~[hazelcast-aws-1.1.jar:1.1]
        at com.hazelcast.aws.impl.DescribeInstances.<init>(DescribeInstances.java:61) ~[hazelcast-aws-1.1.jar:1.1]
        at com.hazelcast.aws.AWSClient.getPrivateIpAddresses(AWSClient.java:47) ~[hazelcast-aws-1.1.jar:1.1]
        at com.hazelcast.cluster.impl.TcpIpJoinerOverAWS.getMembers(TcpIpJoinerOverAWS.java:42) [hazelcast-aws-1.1.jar:1.1]
        at com.hazelcast.cluster.impl.TcpIpJoiner.getPossibleAddresses(TcpIpJoiner.java:404) [hazelcast-3.7.1.jar:1.1]
        at com.hazelcast.cluster.impl.TcpIpJoiner.searchForOtherClusters(TcpIpJoiner.java:507) [hazelcast-3.7.1.jar:1.1]
        at com.hazelcast.internal.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:75) [hazelcast-3.7.1.jar:3.7.1]
        at com.hazelcast.internal.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:42) [hazelcast-3.7.1.jar:3.7.1]
        at com.hazelcast.spi.impl.executionservice.impl.SkipOnConcurrentExecutionDecorator.run(SkipOnConcurrentExecutionDecorator.java:40) [hazelcast-3.7.1.jar:3.7.1]
        at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212) [hazelcast-3.7.1.jar:3.7.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-3.7.1.jar:3.7.1]
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) [hazelcast-3.7.1.jar:3.7.1]
```

I'm pretty sure our config has no access-key though, we're using iam-role only.
Our aws config looks like this:

``` 
            <aws enabled="true">
		<iam-role>xxx_role</iam-role>
                <!--optional, default is us-east-1 -->
                <region>us-east-1</region>
                <!-- optional, only instances belonging to this group will be discovered, default will try all running instances -->
                <security-group-name>xxx_group</security-group-name>
            </aws>
```

Note that even though this exception is constantly being logged (every couple minutes), discovery seemed to be working OK, and our application was responding normally.
Only one of our nodes displayed this behavior. The other nodes were working fine.

I'm on Hazelcast 3.7.1, using hazelcast-aws plugin 1.1.
This issue didn't happen with the old hazelcast-cloud plugin.

**Comment by mesutcelik** [comment]
Thanks @fschuh for the detailed explanation. I think that validation must be moved to XML Config parsing instead of done by `DescribeInstances` constructor.
