### ISSUE TITLE
Fargate discovery doesn't work properly under Quarkus and GraalVM 

### ISSUE THREAD

**Issue by pivovarit** [hazelcast/hazelcast-aws#175]
If you try running Fargate autodiscovery in Quarkus' native mode, you end up with a cryptic stacktrace:

```
Caused by: com.hazelcast.aws.RestClientException: Failure in executing REST call
    at com.hazelcast.aws.RestClient.call(RestClient.java:116)
    at com.hazelcast.aws.RestClient.lambda$callWithRetries$0(RestClient.java:82)
    at com.hazelcast.aws.RetryUtils.retry(RetryUtils.java:51)
    at com.hazelcast.aws.RestClient.callWithRetries(RestClient.java:82)
    at com.hazelcast.aws.RestClient.get(RestClient.java:74)
    at com.hazelcast.aws.AwsMetadataApi.availabilityZoneEc2(AwsMetadataApi.java:63)
    at com.hazelcast.aws.AwsClientConfigurator.resolveRegion(AwsClientConfigurator.java:80)
    at com.hazelcast.aws.AwsClientConfigurator.createAwsClient(AwsClientConfigurator.java:52)
    at com.hazelcast.aws.AwsDiscoveryStrategy.<init>(AwsDiscoveryStrategy.java:75)
    at com.hazelcast.aws.AwsDiscoveryStrategyFactory.newDiscoveryStrategy(AwsDiscoveryStrategyFactory.java:41)
    at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:183)
    at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:141)
    ... 51 more
Caused by: java.net.ConnectException: Invalid argument (connect failed)
    at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_ConnectException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)

```

which can be later traced to be caused by `java.net.HttpURLConnection.getResponseCode` called by the internal HTTP client.

**Comment by pivovarit** [comment]
I believe this _fixed itself_ when one of the newer GraalVM releases showed up.
