### ISSUE TITLE
Stopped working with Hazelcast 3.9+

### ISSUE THREAD

**Issue by Glamdring** [hazelcast/hazelcast-aws#52]
I have the following setup, which used to work with Hazelcast 3.8.6, but fails on AWS:

```
@Bean
    @Profile("!test")
    public HazelcastInstance hazelcast() {
        Config config = new Config();
        config.setProperty("hazelcast.jmx", "true");
        config.setProperty(GroupProperty.PHONE_HOME_ENABLED.getName(), "false");
        config.getGroupConfig().setName(environment);
        if (awsDeployment) {
            config.getPartitionGroupConfig()
                    .setGroupType(PartitionGroupConfig.MemberGroupType.ZONE_AWARE)
                    .setEnabled(true);
            config.setProperty(GroupProperty.DISCOVERY_SPI_ENABLED.getName(), "true");
            JoinConfig joinConfig = config.getNetworkConfig().getJoin();
            joinConfig.getTcpIpConfig().setEnabled(false);
            joinConfig.getAwsConfig().setEnabled(false); // counter-intuitive, but it's a legacy configuration
            joinConfig.getMulticastConfig().setEnabled(false);
            DiscoveryStrategyConfig discoveryStrategy = new DiscoveryStrategyConfig(new AwsDiscoveryStrategyFactory());
            joinConfig.getDiscoveryConfig().getDiscoveryStrategyConfigs().add(discoveryStrategy);
            joinConfig.getDiscoveryConfig().setDiscoveryServiceProvider(new DefaultDiscoveryServiceProvider());
            discoveryStrategy.addProperty("iam-role", iamRole);
            discoveryStrategy.addProperty("region", new DefaultAwsRegionProviderChain().getRegion());
            discoveryStrategy.addProperty("host-header", "ec2.amazonaws.com");
            discoveryStrategy.addProperty("tag-key", "Name");
            discoveryStrategy.addProperty("tag-value", WEB_APP_NODE_TAG_VALUE);
        }

        return Hazelcast.newHazelcastInstance(config);
    }
```

The stacktrace of the error with 3.9+ is:

```
Caused by: java.lang.IllegalArgumentException: Not enough metadata information is provided. At least one of availability zone, rack or host information must be provided with ZONE_AWARE partition group.
        at com.hazelcast.partition.membergroup.ZoneAwareMemberGroupFactory.createInternalMemberGroups(ZoneAwareMemberGroupFactory.java:47)
        at com.hazelcast.partition.membergroup.BackupSafeMemberGroupFactory.createMemberGroups(BackupSafeMemberGroupFactory.java:29)
        at com.hazelcast.internal.partition.impl.PartitionStateManager.createMemberGroups(PartitionStateManager.java:113)
        at com.hazelcast.internal.partition.impl.PartitionStateManager.updateMemberGroupsSize(PartitionStateManager.java:217)
        at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.memberAdded(InternalPartitionServiceImpl.java:358)
        at com.hazelcast.internal.cluster.impl.MembershipManager.sendMembershipEvents(MembershipManager.java:601)
        at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.sendLocalMembershipEvent(ClusterServiceImpl.java:183)
        at com.hazelcast.instance.Node.start(Node.java:369)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:133)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:124)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
```

**Comment by mesutcelik** [comment]
Hi @Glamdring ,
Thanks for raising the issue.

I think you hit the bug here #50 
This is already [fixed](https://github.com/hazelcast/hazelcast/pull/11934) and will be released in hazelcast 3.9.2. You can expect the release within a week so stay tuned!
