### ISSUE TITLE
AWS Discovery for Client does not honor configured connection retry config

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast-aws#57]
When using AWS discovery on a HazelcastClient, if the initial connection fails due to a 503 error being returned from AWS then the connection is not retried as per the configured retry count.

**Comment by mesutcelik** [comment]
Is Hazelcast Client inside or outside AWS?

@sancar 
How does retry work in case of AWS? Do you think the problem above related to HazelcastClient trying to private IPs?

**Comment by vertex-github** [comment]
We tried both in and out - the location of the client isn't the issue here as far as I can tell - when a 503 error is received the connection attempts stop.

**Comment by sancar** [comment]
I checked the code again and in case of the error from Aws calls it should retry properly. 
We had a bug recently on AWS discovery, which we have fixed. You could be hitting that bug.
https://github.com/hazelcast/hazelcast/pull/11248
https://github.com/hazelcast/hazelcast/pull/11169
The fix is available in versions after 3.8.6.
Can I learn the version you are trying? 
Secondly, are you using <aws> config or <discovery-stragies> config ?

**Comment by vertex-github** [comment]
Tried with 3.9.2 and 3.8.3

**Comment by sancar** [comment]
It seems a question of mine was not readable because of unfortunate formatting. 
Here is the question again:
Are you using `aws` config or `discovery-stragies` config ? 
http://docs.hazelcast.org/docs/3.9.3/manual/html-single/index.html#configuring-client-for-aws

http://docs.hazelcast.org/docs/3.9.3/manual/html-single/index.html#discovery-strategy

**Comment by vertex-github** [comment]
discovery-strategy

**Comment by sancar** [comment]
Can you share the logs of the client when failed to retry?

**Comment by vertex-github** [comment]
```
2018-02-28 14:37:34,302Z INFO  [main] com.hazelcast.client.config.ClientClasspathXmlConfig - Configuring Hazelcast Client from 'client-hz-aws.xml'.
2018-02-28 14:37:34,481Z INFO  [main] com.vertex.hz.HZUtil - CWD: /Users/########/WorkingCopies/scratch
2018-02-28 14:37:34,481Z INFO  [main] com.vertex.hz.HZUtil - SysProp (hazelcast.license.file) not set, using default location in JAR (hazelcast.license.txt)
2018-02-28 14:37:34,523Z INFO  [main] com.hazelcast.core.LifecycleService - hz.client_0 [dev] [3.9.2] HazelcastClient 3.9.2 (20180103 - 03b8f41, 17e4ec3) is STARTING
2018-02-28 14:37:34,530Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] MetricsRegistry minimumLevel:MANDATORY
2018-02-28 14:37:34,539Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance runtime.freeMemory
2018-02-28 14:37:34,540Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance runtime.totalMemory
2018-02-28 14:37:34,540Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance runtime.maxMemory
2018-02-28 14:37:34,540Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance runtime.usedMemory
2018-02-28 14:37:34,540Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance runtime.availableProcessors
2018-02-28 14:37:34,541Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance runtime.uptime
2018-02-28 14:37:34,553Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance gc.minorCount
2018-02-28 14:37:34,553Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance gc.minorTime
2018-02-28 14:37:34,553Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance gc.majorCount
2018-02-28 14:37:34,553Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance gc.majorTime
2018-02-28 14:37:34,553Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance gc.unknownCount
2018-02-28 14:37:34,553Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance gc.unknownTime
2018-02-28 14:37:34,556Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance os.committedVirtualMemorySize
2018-02-28 14:37:34,556Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance os.freePhysicalMemorySize
2018-02-28 14:37:34,556Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance os.freeSwapSpaceSize
2018-02-28 14:37:34,556Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance os.processCpuTime
2018-02-28 14:37:34,556Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance os.totalPhysicalMemorySize
2018-02-28 14:37:34,556Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance os.totalSwapSpaceSize
2018-02-28 14:37:34,556Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance os.maxFileDescriptorCount
2018-02-28 14:37:34,556Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance os.openFileDescriptorCount
2018-02-28 14:37:34,556Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance os.processCpuLoad
2018-02-28 14:37:34,556Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance os.systemCpuLoad
2018-02-28 14:37:34,557Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance os.systemLoadAverage
2018-02-28 14:37:34,559Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance thread.threadCount
2018-02-28 14:37:34,560Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance thread.peakThreadCount
2018-02-28 14:37:34,560Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance thread.daemonThreadCount
2018-02-28 14:37:34,560Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance thread.totalStartedThreadCount
2018-02-28 14:37:34,561Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance classloading.loadedClassesCount
2018-02-28 14:37:34,561Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance classloading.totalLoadedClassesCount
2018-02-28 14:37:34,561Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance classloading.unloadedClassCount
2018-02-28 14:37:34,561Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance file.partition[user.home].freeSpace
2018-02-28 14:37:34,562Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance file.partition[user.home].totalSpace
2018-02-28 14:37:34,562Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance file.partition[user.home].usableSpace
2018-02-28 14:37:34,727Z TRACE [main] com.hazelcast.hibernate.serialization.Hibernate3CacheKeySerializerHook - Hibernate3 not available, skipping serializer initialization
2018-02-28 14:37:34,727Z TRACE [main] com.hazelcast.hibernate.serialization.Hibernate3CacheEntrySerializerHook - Hibernate3 not available, skipping serializer initialization
2018-02-28 14:37:34,733Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance executionService.userExecutorQueueSize
2018-02-28 14:37:34,745Z INFO  [main] com.hazelcast.aws.AwsDiscoveryStrategy - Describe instances will be queried with iam-role, please make sure given iam-role have ec2:DescribeInstances policy attached.
2018-02-28 14:37:34,757Z TRACE [main] com.hazelcast.internal.metrics.impl.MetricsRegistryImpl - hz.client_0 [dev] [3.9.2] Registered probeInstance invocations.pendingCalls
2018-02-28 14:37:34,795Z INFO  [main] com.hazelcast.core.LifecycleService - hz.client_0 [dev] [3.9.2] HazelcastClient 3.9.2 (20180103 - 03b8f41, 17e4ec3) is STARTED
2018-02-28 14:37:34,805Z DEBUG [main] com.hazelcast.internal.networking.nio.NioEventLoopGroup - hz.client_0 [dev] [3.9.2] TcpIpConnectionManager configured with Non Blocking IO-threading model: 1 input threads and 1 output threads
2018-02-28 14:37:34,805Z DEBUG [main] com.hazelcast.internal.networking.nio.NioEventLoopGroup - hz.client_0 [dev] [3.9.2] IO threads selector mode is SELECT
2018-02-28 14:37:34,813Z TRACE [main] com.hazelcast.internal.networking.nio.NioThread - hz.client_0 [dev] [3.9.2] Optimized Selector: sun.nio.ch.KQueueSelectorImpl
2018-02-28 14:37:34,817Z TRACE [main] com.hazelcast.internal.networking.nio.NioThread - hz.client_0 [dev] [3.9.2] Optimized Selector: sun.nio.ch.KQueueSelectorImpl
2018-02-28 14:37:34,818Z TRACE [main] com.hazelcast.internal.networking.nio.iobalancer.IOBalancer - hz.client_0 [dev] [3.9.2] Using normal IO Balancer Strategy.
2018-02-28 14:37:34,819Z TRACE [main] com.hazelcast.internal.networking.nio.iobalancer.IOBalancer - hz.client_0 [dev] [3.9.2] I/O Balancer is disabled as there is only a single a pair of I/O threads. Use the 'hazelcast.io.thread.count' property to increase number of I/O Threads.
2018-02-28 14:37:34,940Z WARN  [hz.client_0.cluster-] com.hazelcast.client.connection.ClientConnectionManager - hz.client_0 [dev] [3.9.2] Could not connect to cluster, shutting down the client. java.io.IOException: Server returned HTTP response code: 503 for URL: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&Filter.1.Name=tag%3Atag-key&Filter.1.Value.1=tag-value&Filter.2.Name=instance-state-name&Filter.2.Value.1=running&Version=2016-11-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=NICKSEXAMPLEKEY%2F20180228%2Fus-east-1%2Fec2%2Faws4_request&X-Amz-Date=20180228T143734Z&X-Amz-Expires=30&X-Amz-Security-Token=token&X-Amz-Signature=4ca63c4349b5bf6818a5154e67b0632b2b6391738fc8174873b8abcaaa2c83fc&X-Amz-SignedHeaders=host
2018-02-28 14:37:34,940Z INFO  [hz.client_0.clientShutdown-] com.hazelcast.core.LifecycleService - hz.client_0 [dev] [3.9.2] HazelcastClient 3.9.2 (20180103 - 03b8f41, 17e4ec3) is SHUTTING_DOWN
2018-02-28 14:37:34,940Z TRACE [hz.client_0.clientShutdown-] com.hazelcast.internal.networking.nio.NioEventLoopGroup - hz.client_0 [dev] [3.9.2] Shutting down IO Threads... Total: 2
2018-02-28 14:37:34,942Z TRACE [hz.hz.client_0.IO.thread-out-0] com.hazelcast.internal.networking.nio.NioThread - hz.client_0 [dev] [3.9.2] Closing selector for:hz.hz.client_0.IO.thread-out-0
2018-02-28 14:37:34,943Z INFO  [hz.client_0.clientShutdown-] com.hazelcast.core.LifecycleService - hz.client_0 [dev] [3.9.2] HazelcastClient 3.9.2 (20180103 - 03b8f41, 17e4ec3) is SHUTDOWN
2018-02-28 14:37:34,943Z TRACE [hz.hz.client_0.IO.thread-in-0] com.hazelcast.internal.networking.nio.NioThread - hz.client_0 [dev] [3.9.2] Closing selector for:hz.hz.client_0.IO.thread-in-0
Exception in thread "main" com.hazelcast.core.HazelcastException: java.io.IOException: Server returned HTTP response code: 503 for URL: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&Filter.1.Name=tag%3Atag-key&Filter.1.Value.1=tag-value&Filter.2.Name=instance-state-name&Filter.2.Value.1=running&Version=2016-11-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=NICKSEXAMPLEKEY%2F20180228%2Fus-east-1%2Fec2%2Faws4_request&X-Amz-Date=20180228T143734Z&X-Amz-Expires=30&X-Amz-Security-Token=token&X-Amz-Signature=4ca63c4349b5bf6818a5154e67b0632b2b6391738fc8174873b8abcaaa2c83fc&X-Amz-SignedHeaders=host
   at com.hazelcast.util.ExceptionUtil$1.create(ExceptionUtil.java:40)
   at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:124)
   at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:69)
   at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:129)
   at com.hazelcast.aws.AwsDiscoveryStrategy.discoverNodes(AwsDiscoveryStrategy.java:167)
   at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:74)
   at com.hazelcast.client.spi.impl.discovery.DiscoveryAddressProvider.loadAddresses(DiscoveryAddressProvider.java:44)
   at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getPossibleMemberAddresses(ClientConnectionManagerImpl.java:918)
   at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.connectToClusterInternal(ClientConnectionManagerImpl.java:835)
   at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.access$1500(ClientConnectionManagerImpl.java:101)
   at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:882)
   at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:878)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at java.lang.Thread.run(Thread.java:748)
   at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
   at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&Filter.1.Name=tag%3Atag-key&Filter.1.Value.1=tag-value&Filter.2.Name=instance-state-name&Filter.2.Value.1=running&Version=2016-11-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=NICKSEXAMPLEKEY%2F20180228%2Fus-east-1%2Fec2%2Faws4_request&X-Amz-Date=20180228T143734Z&X-Amz-Expires=30&X-Amz-Security-Token=token&X-Amz-Signature=4ca63c4349b5bf6818a5154e67b0632b2b6391738fc8174873b8abcaaa2c83fc&X-Amz-SignedHeaders=host
   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
   at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
   at com.hazelcast.aws.impl.DescribeInstances.callService(DescribeInstances.java:244)
   at com.hazelcast.aws.impl.DescribeInstances.execute(DescribeInstances.java:227)
   at com.hazelcast.aws.AWSClient.getAddresses(AWSClient.java:56)
   at com.hazelcast.aws.AwsDiscoveryStrategy.discoverNodes(AwsDiscoveryStrategy.java:146)
   ... 13 more
2018-02-28 14:37:34,945Z TRACE [hz.hz.client_0.IO.thread-out-0] com.hazelcast.internal.networking.nio.NioThread - hz.client_0 [dev] [3.9.2] hz.hz.client_0.IO.thread-out-0 finished
2018-02-28 14:37:34,945Z TRACE [hz.hz.client_0.IO.thread-in-0] com.hazelcast.internal.networking.nio.NioThread - hz.client_0 [dev] [3.9.2] hz.hz.client_0.IO.thread-in-0 finished

Process finished with exit code 1


<?xml version="1.0" encoding="UTF-8"?>
<hazelcast-client xsi:schemaLocation="http://www.hazelcast.com/schema/client-config http://www.hazelcast.com/schema/hazelcast-client-config-3.9.xsd"
                  xmlns="http://www.hazelcast.com/schema/client-config"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <group>
        <name>dev</name>
        <password>########</password>
    </group>

    <properties>
        <property name="hazelcast.logging.type">slf4j</property>
        <property name="hazelcast.phone.home.enabled">false</property>
        <property name="hazelcast.discovery.enabled">true</property>
    </properties>

    <network>

        <connection-timeout>10000</connection-timeout>
        <connection-attempt-period>3000</connection-attempt-period>
        <connection-attempt-limit>60</connection-attempt-limit>

        <discovery-strategies>
            <discovery-strategy enabled="true" class="com.hazelcast.aws.AwsDiscoveryStrategy">
                <properties>
                    <!--<property name="access-key">not-needed</property>-->
                    <!--<property name="secret-key">not-needed</property>-->
                    <property name="iam-role">Nicks_Test_IAM_Role</property>
                    <property name="tag-key">tag-key</property>
                    <property name="tag-value">tag-value</property>
                    <property name="hz-port">11415</property>
                </properties>
            </discovery-strategy>
        </discovery-strategies>
    </network>

</hazelcast-client>
```

**Comment by sancar** [comment]
Thanks for the logs. The problem is obvious with this log. `connectToClusterInternal` needs to be inside try/catch block . Any error should be cached and we need to continue to other attempts. We will address this in next patch of the hazelcast main project. I have opened an issue there for this fix
https://github.com/hazelcast/hazelcast/issues/12457
