### ISSUE TITLE
NumberFormat Exception thrown for Port Range

### ISSUE THREAD

**Issue by JohnZoldos** [hazelcast/hazelcast-aws#84]
When configuring the port range for the Hazelcast Client, configuring the port range as such:   
             
     <property name="hz-port">5701-5708</property>

ends up throwing a number format exception. If I don't specify a port range then the default value should still be 5701-5708, but this doesn't throw an exception. But, in this case, the client doesn't search for any ports after 5701. If it can't connect on port 5701, it merely tries a second time. If it doesn't connect the second time, it gives up.

Here is the stack trace for the NumberFormatException:
`
INFO: hz.client_0 [FB] [3.10.5] HazelcastClient 3.10.5 (20180913 - 6ffa2ee) is STARTING
java.lang.RuntimeException: Failed to configure discovery strategies
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:150)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:57)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.initDiscoveryService(HazelcastClientInstanceImpl.java:430)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:253)
	at com.hazelcast.client.HazelcastClient$1.createHazelcastInstanceClient(HazelcastClient.java:55)
	at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:75)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:72)
	at com.john.engine.imdg.hazelcast.util.HazelcastMapEntryRemover.<init>(HazelcastMapEntryRemover.java:88)
	at com.john.engine.imdg.hazelcast.util.HazelcastMapEntryRemover.main(HazelcastMapEntryRemover.java:248)
Caused by: java.lang.NumberFormatException: For input string: "5701-5708"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.hazelcast.config.properties.PropertyTypeConverter$3.convert(PropertyTypeConverter.java:58)
	at com.hazelcast.spi.discovery.impl.DiscoveryServicePropertiesUtil.prepareProperties(DiscoveryServicePropertiesUtil.java:67)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:183)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:142)
	... 9 more
`

**Comment by leszko** [comment]
Is it still an issue?

To me it looks like you're using an old version of the `hazelcast-aws` plugin. Could you try with the latest versions?
- `hazelcast:3.11`
- `hazelcast-aws:2.3`

**Comment by googlielmo** [comment]
Closing for inactivity. Please feel free to open issue again if needed.
